version: '3.9'

services:
  geoapi:
    build: .
    image: local/geoapi:dev
    ports:
    - target: 8080
      published: 8080
      protocol: tcp
    volumes:
      - type: bind
        source: ./res
        target: /usr/src/app/res