openapi: 3.0.1
info:
  title: GEO API PT
  description: Dados gratuitos e abertos para Portugal sobre regiões administrativas oficiais, georreferenciação e códigos postais
  version: '1.0'
servers:
  - url: /
  
components:
  parameters:
    json:
      in: query
      name: json
      required: false
      schema:
        type: string
      description: Ativa resposta em JSON
      examples:
        1:
          value: '1'
          summary: Ativa resposta em JSON
        true:
          value: 'true'
          summary: Ativa resposta em JSON

paths:
  /:
    summary: Página principal
    get:
      responses:
        '200':
          description: Página principal
          content:
            text/html:
              schema:
                type: string
  
  /gps:
    summary: Distrito, Município e Freguesia através de coordenadas GPS (nos parâmetros da query)
    get:
      parameters:
        - in: query
          name: lat
          required: true
          schema:
            type: string
            example: '40.153687'
          description: Latitude do ponto
        - in: query
          name: lon
          required: true
          schema:
            type: string
            example: '-8.514602'
          description: Longitude do ponto
        - in: query
          name: detalhes
          required: false
          schema:
            type: string
            example: '1'
          description: Ativa apresentação de detalhes de Freguesia e Município
        - $ref: '#/components/parameters/json'
      responses:
        '200':
          description: Distrito, Município e Freguesia através de coordenadas GPS
          content:
            application/json:
              schema:
                type: string

  /gps/{coordenadas}:
    summary: Distrito, Município e Freguesia através de coordenadas GPS
    get:
      parameters:
        - in: path
          name: coordenadas
          required: true
          schema:
            type: string
            example: '40.153687,-8.514602'
          allowReserved: true
          description: Coordenadas (latitude e longitude) do ponto
        - $ref: '#/components/parameters/json'
      responses:
        '200':
          description: Distrito, Município e Freguesia através de coordenadas GPS
          content:
            application/json:
              schema:
                type: string

  /gps/{coordenadas}/detalhes:
    summary: Distrito, Município e Freguesia através de coordenadas GPS, com detalhes sobre respectivos Município e Freguesia
    get:
      parameters:
        - in: path
          name: coordenadas
          required: true
          schema:
            type: string
            example: '40.153687,-8.514602'
          allowReserved: true
          description: Coordenadas (latitude e longitude) do ponto
        - $ref: '#/components/parameters/json'
      responses:
        '200':
          description: Distrito, Município e Freguesia através de coordenadas GPS, com detalhes sobre respectivos Município e Freguesia
          content:
            application/json:
              schema:
                type: string
  
  /municipios:
    summary: Lista de todos os Municípios
    get:
      parameters:
        - in: query
          name: nome
          required: false
          schema:
            type: string
          allowReserved: true
          description: Nome do Município
        - in: query
          name: codigo
          required: false
          schema:
            type: integer
          description: Código do Município
        - in: query
          name: nif
          required: false
          schema:
            type: integer
          description: NIF do Município
        - in: query
          name: codigopostal
          required: false
          schema:
            type: string
          description: Código Postal do Município
        - in: query
          name: email
          required: false
          schema:
            type: string
          allowReserved: true
          description: Email do Município
        - in: query
          name: telefone
          required: false
          schema:
            type: integer
          description: Telefone do Município
        - in: query
          name: fax
          required: false
          schema:
            type: integer
          description: Fax do Município
        - in: query
          name: sitio
          required: false
          schema:
            type: string
          allowReserved: true
          description: Website do Município
        - in: query
          name: codigoine
          required: false
          schema:
            type: integer
          description: Código INE do Município
        - $ref: '#/components/parameters/json'
      responses:
        '200':
          description: Lista de todos os Municípios
          content:
            application/json:
              schema:
                type: string

  /municipios/{municipio}:
    summary: Detalhes sobre Município  
    get:
      parameters:
        - in: path
          name: municipio
          required: true
          schema:
            type: string
            example: évora
          allowReserved: true
          description: Município
        - $ref: '#/components/parameters/json'
      responses:
        '200':
          description: Detalhes do Município
          content:
            application/json:
              schema:
                type: string

  /municipio/{municipio}:
    $ref: '#/paths/~1municipios~1{municipio}'
  
  /municipios/{municipio}/freguesias:
    summary: Lista de Freguesias no Município
    get:
      parameters:
        - in: path
          name: municipio
          required: true
          schema:
            type: string
            example: évora
          allowReserved: true
          description: Município
        - $ref: '#/components/parameters/json'
      responses:
        '200':
          description: Lista de Freguesias no Município
          content:
            application/json:
              schema:
                type: string

  /municipio/{municipio}/freguesias:
    $ref: '#/paths/~1municipios~1{municipio}~1freguesias'
  
  /freguesias:
    summary: Lista de todas as Freguesias
    get:
      parameters:
        - in: query
          name: nome
          required: false
          schema:
            type: string
          allowReserved: true
          description: Nome da Freguesia
        - in: query
          name: municipio
          required: false
          schema:
            type: string
          allowReserved: true
          description: Município da Freguesia
        - in: query
          name: codigo
          required: false
          schema:
            type: integer
          description: Código da Freguesia
        - in: query
          name: nif
          required: false
          schema:
            type: integer
          description: NIF da Freguesia
        - in: query
          name: codigopostal
          required: false
          schema:
            type: string
          description: Código Postal da Freguesia
        - in: query
          name: email
          required: false
          schema:
            type: string
          allowReserved: true
          description: Email da Freguesia
        - in: query
          name: telefone
          required: false
          schema:
            type: integer
          description: Telefone da Freguesia
        - in: query
          name: fax
          required: false
          schema:
            type: integer
          description: Fax da Freguesia
        - in: query
          name: sitio
          required: false
          schema:
            type: string
          allowReserved: true
          description: Website da Freguesia
        - in: query
          name: codigoine
          required: false
          schema:
            type: integer
          description: Código INE da Freguesia
        - $ref: '#/components/parameters/json'
      responses:
        '200':
          description: Lista de todas as Freguesias
          content:
            application/json:
              schema:
                type: string

  /freguesias/{freguesia}:
    summary: Detalhes sobre Freguesia(s)
    get:
      parameters:
        - in: path
          name: freguesia
          required: true
          schema:
            type: string
            example: serzedelo
          allowReserved: true
          description: Freguesia
        - in: query
          name: municipio
          required: false
          schema:
            type: string
          allowReserved: true
          description: Município da Freguesia
        - in: query
          name: codigo
          required: false
          schema:
            type: integer
          description: Código da Freguesia
        - in: query
          name: nif
          required: false
          schema:
            type: integer
          description: NIF da Freguesia
        - in: query
          name: codigopostal
          required: false
          schema:
            type: string
          description: Código Postal da Freguesia
        - in: query
          name: email
          required: false
          schema:
            type: string
          allowReserved: true
          description: Email da Freguesia
        - in: query
          name: telefone
          required: false
          schema:
            type: integer
          description: Telefone da Freguesia
        - in: query
          name: fax
          required: false
          schema:
            type: integer
          description: Fax da Freguesia
        - in: query
          name: sitio
          required: false
          schema:
            type: string
          allowReserved: true
          description: Website da Freguesia
        - in: query
          name: codigoine
          required: false
          schema:
            type: integer
          description: Código INE da Freguesia
        - $ref: '#/components/parameters/json'
      responses:
        '200':
          description: Lista de Freguesias que correspondem à procura
          content:
            application/json:
              schema:
                type: string

  /freguesia/{freguesia}:
    $ref: '#/paths/~1freguesias~1{freguesia}'
                
  /municipios/{municipio}/freguesias/{freguesia}:
    summary: Detalhes sobre Freguesia de um determinado Município
    get:
      parameters:
        - in: path
          name: municipio
          required: true
          schema:
            type: string
            example: guimarães
          allowReserved: true
          description: Município
        - in: path
          name: freguesia
          required: true
          schema:
            type: string
            example: serzedelo
          allowReserved: true
          description: Município
        - $ref: '#/components/parameters/json'
      responses:
        '200':
          description: Detalhes da Freguesia
          content:
            application/json:
              schema:
                type: string

  /municipio/{municipio}/freguesias/{freguesia}:
    $ref: '#/paths/~1municipios~1{municipio}~1freguesias~1{freguesia}'
  
  /municipios/{municipio}/freguesia/{freguesia}:
    $ref: '#/paths/~1municipios~1{municipio}~1freguesias~1{freguesia}'

  /municipio/{municipio}/freguesia/{freguesia}:
    $ref: '#/paths/~1municipios~1{municipio}~1freguesias~1{freguesia}'

  /distritos:
    summary: Lista de todos os Distritos
    get:
      parameters: 
        - $ref: '#/components/parameters/json'
      responses:
        '200':
          description: Lista de todos os Distritos
          content:
            application/json:
              schema:
                type: string

  /distritos/municipios:
    summary: Lista de todos os Distritos com respetivos Municípios
    get:
      parameters: 
        - $ref: '#/components/parameters/json'
      responses:
        '200':
          description: Lista de todos os Distritos com respetivos Municípios
          content:
            application/json:
              schema:
                type: string
                
  /distritos/{distrito}/municipios:
    summary: Lista de Municípios do Distrito
    get:
      parameters:
        - in: path
          name: distrito
          required: true
          schema:
            type: string
            example: porto
          allowReserved: true
          description: Distrito
        - $ref: '#/components/parameters/json'
      responses:
        '200':
          description: Lista de Municípios do Distrito
          content:
            application/json:
              schema:
                type: string
  
  /distrito/{distrito}/municipios:
    $ref: '#/paths/~1distritos~1{distrito}~1municipios'
                
  /cp/{cp}:
    summary: Detalhes sobre Código Postal
    get:
      parameters:
        - in: path
          name: cp
          required: true
          schema:
            type: string
            pattern: '^\d{4}(-\d{3})?$'
          examples:
            cp4:
              value: '2495'
              summary: Código Postal CP4
            cp7:
              value: '2495-300'
              summary: Código Postal CP7
          description: Código Postal
        - $ref: '#/components/parameters/json'
      responses:
        '200':
          description: Detalhes sobre Código Postal CP7
          content:
            application/json:
              schema:
                type: string
  
  /shieldsio/requestslasthour:
    summary: Pedidos por hora
    get:
      responses:
        '200':
          description: Pedidos por hora
          content:
            application/json:
              schema:
                type: string
                
  /shieldsio/requestslastday:
    summary: Pedidos por dia
    get:
      responses:
        '200':
          description: Pedidos por dia
          content:
            application/json:
              schema:
                type: string
