# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Test API server

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

defaults:
  run:
    shell: bash -l {0}

jobs:
  build:
    strategy:
      matrix:
        platform: [ubuntu-latest]
        node-version: [16] # node 16 is used in production
        
    runs-on: ${{ matrix.platform }}

    steps:
    - name: Main checkout
      uses: actions/setup-node@v4
      with:
        path: main
    - uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
    - name: Checkout resources private repo
      uses: actions/setup-node@v4
      with:
        repository: geoapi-pt/resources
        token: ${{ secrets.GH_PAT }}
        path: resources
    - run: ls ${GITHUB_WORKSPACE} -lh
    - run: df . -h
    - name: Install npm packages
      run: cd resources && npm ci --omit=dev && cd ../main && npm ci --omit=dev
    - run: npm test

